lexer grammar MiniGoScanner;


PACKAGE : 'package' ;
PyCOMA : ';' ;
DOSP : ':' ;
VAR : 'var' ;
PARIZQ : '(' ;
PARDER : ')' ;
IGUAL : '=' ;
TYPE : 'type' ;
FUNC : 'func' ;
COMA : ',' ;
PUNTO : '.' ;
CORCHIZQ : '[' ;
CORCHDER : ']' ;
STRUCT : 'struct' ;
LLAVEIZQ : '{' ;
LLAVEDER : '}' ;
MULTI : '*' ;
DIV : '/' ;
PORCENT : '%' ;
MAYORM : '<<' ;
MEMORM : '>>' ;
AND : '&' ;
BITCLE : '&^' ;
SUMA : '+' ;
RESTA : '-' ;
OR : '|' ;
XOR : '^';
IDENTICO : '==' ;
DIFERENTE : '!=' ;
MAYOR : '<' ;
MAYORIG : '<=' ;
MENOR : '>' ;
MENORIG : '>=' ;
ANDD : '&&' ;
ORD : '||' ;
EXCL : '!' ;
APPEND : 'append' ;
LEN : 'len' ;
CAP : 'cap' ;
PRINT : 'print' ;
PRINTLN : 'println' ;
RETURN : 'return' ;
BREAK : 'break' ;
CONTINUE : 'continue' ;
SUMAD : '++' ;
RESTAD : '--' ;
ASSIGN : ':=' ;
INCREM : '+=' ;
ANDCOMP : '&=' ;
DECREME : '-=' ;
ASSIGNOR : '|=' ;
ASSIGNMULT : '*=' ;
ASSIGNXOR : '^=' ;
ASSIGMA : '<<=' ;
ASSIGNME : '>>=' ;
ASSIGNBIT : '&^=' ;
ASSIGNPOR : '%=' ;
ASSINGDIV : '/=' ;
IF : 'if' ;
ELSE : 'else' ;
FOR : 'for' ;
SWITCH : 'switch' ;
CASE : 'case' ;
DEFAULT : 'default' ;
ID : [a-zA-Z_][a-zA-Z0-9_]*;
INT : DIGIT+ ;
FLOAT :  DIGIT+ '.' DIGIT*| '.' DIGIT+ ;
RUNE : '\'' (~['\\\r\n] | '\\' [abfnrtv\\'"]) '\'';
RAWSTRING : '`' ~'`'* '`';
INTERPRETEDSTRING : '"' (~["\\\r\n] | '\\' [abfnrtv'"])* '"';

fragment DIGIT:  [0-9] ;

COMENT : '//' ~[\r\n]* -> skip;
COMENTM : '/*' .*? '*/' -> skip;
WS  :   [ \t\n\r]+ -> skip ;